FROM python:3.10-slim

WORKDIR /app

RUN pip install fastapi uvicorn

# Copiamos el código
COPY . .

# Comando de arranque
CMD ["uvicorn", "inference_service.main:app", "--host", "0.0.0.0", "--port", "8000"]